import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Load vault config (if exists)
function getVaultConfig() {
  const configPath = path.join(process.cwd(), '.vault-config.json');
  if (fs.existsSync(configPath)) {
    try {
      return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    } catch (e) {
      console.warn('⚠️  Could not read .vault-config.json:', e.message);
    }
  }
  return null;
}

// Copy files to user's vault
function copyToVault(devVaultPath) {
  const config = getVaultConfig();
  if (!config || !config.vaultPath) {
    return; // No vault config, skip copying
  }

  const pluginName = config.pluginName || 'full-calendar-remastered';
  const targetDir = path.join(config.vaultPath, '.obsidian', 'plugins', pluginName);
  
  // Ensure target directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
    console.log(`📁 Created plugin directory: ${targetDir}`);
  }

  // Files to copy
  const filesToCopy = [
    { src: path.join(devVaultPath, 'main.js'), dest: path.join(targetDir, 'main.js') },
    { src: path.join(devVaultPath, 'styles.css'), dest: path.join(targetDir, 'styles.css') },
    { src: path.join(process.cwd(), 'manifest.json'), dest: path.join(targetDir, 'manifest.json') }
  ];

  const now = new Date();
  filesToCopy.forEach(({ src, dest }) => {
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      // Update file modification time so Hot Reload detects the change
      fs.utimesSync(dest, now, now);
      console.log(`✅ Copied ${path.basename(src)} → ${config.vaultPath}`);
    }
  });
}

async function build() {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/comment",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/highlight",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/panel",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/tooltip",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    target: "es2016",
    logLevel: "info",
    minify: prod,
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    entryNames: "[name]",
    plugins: [
      {
        name: 'rename-css-plugin',
        setup(build) {
          build.onEnd(() => {
            const cssOutputDir = "obsidian-dev-vault/.obsidian/plugins/full-calendar-remastered";
            const oldPath = path.join(cssOutputDir, "main.css");
            const newPath = path.join(cssOutputDir, "styles.css");

            if (fs.existsSync(oldPath)) {
              fs.renameSync(oldPath, newPath);
              console.log(" | Renamed CSS to styles.css");
            } else {
              console.warn("⚠️ CSS file not found to rename");
            }

            // Copy to user's vault after build
            copyToVault(cssOutputDir);
          });
        }
      }
    ],
    outfile: "obsidian-dev-vault/.obsidian/plugins/full-calendar-remastered/main.js",
  });

  if (!prod) {
    context.watch();
    console.log('Watching for changes...');
  } else {
    await context.rebuild();
    context.dispose();
  }
}

build().catch(() => process.exit(1));