# mkdocs.yaml
site_name: Full Calendar Remastered
repo_url: https://github.com/YouFoundJK/plugin-full-calendar
repo_name: YouFoundJK/plugin-full-calendar
theme:
    name: material
    icon:
        repo: fontawesome/brands/square-github
    font:
        text: Work Sans
    features:
        - navigation.instant
        - navigation.sections
        - navigation.expand
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: light blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: blue grey
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
markdown_extensions:
    - toc:
          permalink: true
    - admonition # Add admonition for notes and warnings

nav:
    - Introduction: index.md
    - What's New: whats_new.md
    - Changelog: changelog.md
    - Getting Started: getting_started.md
    - Calendar Types:
          - Full Note Calendar: calendars/local.md
          - Daily Note Calendar: calendars/dailynote.md
          - Remote (ICS): calendars/ics.md
          - Remote (CalDAV): calendars/caldav.md
          - Remote (Google Calender): calendars/gcal.md
    - Events & Features:
          - Event Management: events/manage.md
          - Recurring Events: events/recurring.md
          - Tasks: events/tasks.md
          - Category Coloring: events/categories.md
          - Timeline View Usage: views/timeline_view.md
          - Workspaces: views/workspaces.md
          - Timezone Support: events/timezones.md
          - Hover & Context Menu: events/hover_context.md
    - ChronoAnalyser: 
          - Chrono Analyser: chrono_analyser/introduction.md
          - Use Cases: chrono_analyser/usecases.md
          - FAQ & Troubleshooting: chrono_analyser/faq.md
    - Settings:
          - Calendar Sources: settings/sources.md
          - Display & Behavior: settings/fc_config.md
    - Advanced:
          - Dataview Integration: advanced/dataview.md
          - Data Integrity and File Modifications: advanced/data_integrity.md
    - Privacy & Terms:
          - Privacy Policy: advanced/privacy-policy.md
          - Terms of Service: advanced/terms-of-service.md